<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SliceTranscribe</AssemblyName>
    <RootNamespace>SliceTranscribe</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SliceControl\SliceControl.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
